sonar.projectKey=mobigen-voicephishing-lab_golang-template_70eb7439-dee2-4570-8a94-51215303942d
sonar.projectName=golang-template

sonar.sources=.
sonar.exclusions=vendor/**,docs/**,build/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=build/coverage.out
