// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mobigen/golang-web-template/controllers (interfaces: SampleUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/mobigen/golang-web-template/models"
)

// MockSampleUsecase is a mock of SampleUsecase interface.
type MockSampleUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSampleUsecaseMockRecorder
}

// MockSampleUsecaseMockRecorder is the mock recorder for MockSampleUsecase.
type MockSampleUsecaseMockRecorder struct {
	mock *MockSampleUsecase
}

// NewMockSampleUsecase creates a new mock instance.
func NewMockSampleUsecase(ctrl *gomock.Controller) *MockSampleUsecase {
	mock := &MockSampleUsecase{ctrl: ctrl}
	mock.recorder = &MockSampleUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSampleUsecase) EXPECT() *MockSampleUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSampleUsecase) Create(arg0 *models.Sample) (*models.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*models.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSampleUsecaseMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSampleUsecase)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockSampleUsecase) Delete(arg0 int) (*models.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(*models.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSampleUsecaseMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSampleUsecase)(nil).Delete), arg0)
}

// GetAll mocks base method.
func (m *MockSampleUsecase) GetAll() (*[]models.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*[]models.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSampleUsecaseMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSampleUsecase)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockSampleUsecase) GetByID(arg0 int) (*models.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0)
	ret0, _ := ret[0].(*models.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSampleUsecaseMockRecorder) GetByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSampleUsecase)(nil).GetByID), arg0)
}

// Update mocks base method.
func (m *MockSampleUsecase) Update(arg0 *models.Sample) (*models.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(*models.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSampleUsecaseMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSampleUsecase)(nil).Update), arg0)
}
